name: Lint Code

on:
  [ pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Install modules
        run: yarn install

      - name: Build packages
        run: yarn lerna:build

      - name: Link dependencies
        run: yarn lerna:link

      - name: Run eslint
        run: yarn lint